# Generated by Django 3.2.21 on 2023-09-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='user',
            new_name='contributer',
        ),
    ]
