# Generated by Django 3.2.21 on 2023-09-20 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='place_name',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='contributer',
        ),
        migrations.AlterField(
            model_name='place',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='favourited',
            field=models.ManyToManyField(blank=True, related_name='favourited_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
