# Generated by Django 3.2.20 on 2023-09-11 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places_app.place')),
            ],
        ),
    ]
