# Generated by Django 3.2.21 on 2023-09-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=51.54151543964534),
            preserve_default=False,
        ),
    ]
