# Generated by Django 3.2.21 on 2023-09-21 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='contributer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL),
        ),
    ]
