# Generated by Django 3.2.21 on 2023-09-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_app', '0002_place_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo_url',
            field=models.URLField(default='http://placekitten.com/200/300'),
            preserve_default=False,
        ),
    ]
